PROCOLLAB-github/procollab

src/index.html

CU-861m529v8_-----_Egor

---

src/app/office/shared/header/header.component.html

CU-861m52d4q_------_Egor

---

src/app/office/profile/detail/profile-detail.component.html
src/app/office/profile/edit/edit.component.html
src/app/office/profile/edit/edit.component.scss
src/app/office/projects/edit/edit.component.html
src/app/office/projects/edit/edit.component.scss

CU-861m524zh_-------_Egor

---

src/app/office/profile/detail/profile-detail.component.html

CU-861m51jq2_-----------_Egor

---

src/app/office/projects/edit/edit.component.html

CU-861m7wq8t_----_Egor

---

src/app/office/office.component.html
src/app/office/profile/edit/edit.component.html
src/app/office/profile/edit/edit.component.scss
src/app/office/projects/edit/edit.component.html
src/app/office/projects/edit/edit.component.scss
src/app/office/projects/edit/edit.component.ts
src/app/ui/directives/editor-submit-button.directive.spec.ts
src/app/ui/directives/editor-submit-button.directive.ts
src/app/ui/ui.module.ts

CU-861m7wqb0_-------------_Egor

---

src/app/office/office-routing.module.ts
src/app/office/office.module.ts
src/app/office/projects/edit/edit.component.html
src/app/office/projects/edit/edit.component.scss
src/app/office/projects/edit/edit.component.ts
src/app/office/projects/projects-routing.module.ts
src/app/office/projects/projects.module.ts

CU-861m8j281_---_Egor

---

angular.json
src/app/office/projects/edit/edit.component.html
src/app/office/projects/edit/edit.component.scss

CU-861m7knnk_--------_Egor

---

src/app/office/projects/list/list.component.ts
src/app/office/projects/projects.component.html
src/app/office/projects/projects.component.ts
src/app/office/services/project.service.ts

CU-861m7wr1d_----_Egor

---

src/app/office/projects/responses/responses.component.ts
src/app/office/shared/response-card/response-card.component.html
src/app/office/shared/response-card/response-card.component.scss

CU-861m7kmaa_---------_Egor

---

src/app/office/projects/detail/detail.component.scss
src/app/office/shared/nav/nav.component.scss

CU-861m7km4b_--------_Egor

---

src/app/office/vacancy/send/send.component.html
src/app/office/vacancy/send/send.component.scss

CU-861m9jgme_------_Egor

---

src/app/office/projects/edit/edit.component.html
src/app/office/projects/edit/edit.component.scss
src/app/office/projects/projects.component.html
src/app/office/projects/projects.component.ts
src/app/ui/components/avatar-control/avatar-control.component.ts

CU-861m9hg3n_---_Egor

---

src/app/office/profile/edit/edit.component.html
src/app/office/profile/edit/edit.component.scss
src/app/office/profile/edit/edit.component.ts

CU-861m9jgnk_-----_Egor

---

src/app/office/projects/list/list.component.scss
src/app/office/shared/project-card/project-card.component.scss
src/app/ui/components/num-slider/num-slider.component.html
src/app/ui/components/num-slider/num-slider.component.ts

CU-861m9xebb_-----_Egor

---

src/app/auth/register/register.component.html
src/app/auth/register/register.component.ts
src/app/core/services/validation.service.ts
src/app/error/models/error-message.ts

CU-861mb1rab_--------14-----_Egor

---

src/app/office/profile/detail/profile-detail.component.html
src/app/office/profile/detail/profile-detail.component.scss

CU-861m9xecj_-------_Egor

---

src/app/ui/components/search/search.component.scss

CU-861m52dmt_-------_Egor

---

src/app/office/shared/header/header.component.html
src/app/office/shared/header/header.component.scss
src/styles/_responsive.scss

CU-861mb1ujd_-----960px_Egor

---

src/app/office/projects/projects-filter/projects-filter.component.scss

CU-861mb1u6k_------_Egor

---

src/app/office/profile/detail/profile-detail.component.html

CU-861mbphbf_--------_Egor

---

src/app/auth/services/auth.service.ts
src/app/core/services/api.service.ts
src/app/core/services/file.service.ts
src/app/office/mentors/mentors.component.ts
src/app/office/profile/edit/edit.component.ts
src/app/office/services/nav.service.ts
src/app/office/shared/nav/nav.component.html
src/app/office/shared/nav/nav.component.ts
src/app/ui/components/avatar-control/avatar-control.component.ts

CU-861m9qx01_---_Egor

---

src/app/ui/components/textarea/textarea.component.html

CU-861mb1tjn_------_Egor

---

src/app/core/interceptors/bearer-token.interceptor.ts

CU-861mju169_-_Egor

---

src/app/auth/register/register.component.html

CU-85zrv5qdh_placeholder-----_Egor

---

src/app/office/projects/projects-filter/projects-filter.component.html

CU-85zrv3u6x_---_Egor

---

src/app/error/models/error-message.ts
src/app/office/profile/edit/edit.component.html
src/app/office/profile/edit/edit.component.scss
src/app/office/projects/edit/edit.component.html
src/app/office/projects/edit/edit.component.scss
src/app/ui/components/avatar-control/avatar-control.component.html
src/app/ui/components/avatar-control/avatar-control.component.scss
src/app/ui/components/avatar-control/avatar-control.component.ts

CU-85zrvk9bx_-----_Egor

---

src/app/office/shared/header/header.component.scss

CU-861mb1upq_-border-radius---_Egor

---

src/app/office/shared/member-card/member-card.component.html
src/app/office/shared/member-card/member-card.component.scss
src/app/office/shared/member-card/member-card.component.ts
src/app/office/shared/message-input/message-input.component.scss
src/app/office/shared/project-card/project-card.component.scss
src/styles/_colors.scss
src/styles/_typography.scss
src/styles/pages/_members.scss

CU-861mjnhne_--_Egor

---

src/app/office/office.component.html
src/app/office/shared/header/header.component.html

redirect to home when clicking on logo

CU-85zrw88vr_--------_Egor

---

src/app/office/projects/edit/edit.component.scss

CU-85zrw87bn_---_Egor

---

src/app/ui/directives/editor-submit-button.directive.ts
src/styles/_typography.scss

CU-85zrw87gu_----_Egor

---

src/app/office/shared/project-card/project-card.component.scss

CU-861mrhg1m_----15-_Egor

---

src/app/office/onboarding/onboarding/onboarding.component.scss

CU-861mrhd9k_---1-_Egor

---

src/app/auth/services/auth.service.ts

CU-85zrzz9jp_----_Egor

---

src/app/office/projects/list/list.component.html
src/app/office/projects/list/list.component.scss

CU-85zt24jpe_--_Egor

---

src/app/auth/models/user.model.ts
src/app/office/profile/detail/profile-detail.component.html
src/app/office/profile/detail/profile-detail.component.scss
src/app/office/projects/projects.module.ts

CU-85zt24xdj_----_Egor

---

src/app/office/projects/detail/responses/responses.resolver.ts

CU-85ztd50h0_-----_Egor

---

src/app/office/projects/list/list.component.scss

CU-85ztb00r5_------_Egor

---

src/app/office/projects/detail/info/info.component.scss

CU-85ztdr626_--_Egor

---

src/styles.scss

CU-85zteu5au_Loader---_Egor

---

src/app/auth/services/auth.service.ts
src/app/office/onboarding/stage-zero/stage-zero.component.html
src/app/ui/components/input/input.component.html
src/app/ui/components/input/input.component.ts

CU-861n0kzxf_-_Egor

---

src/app/ui/components/snackbar/snackbar.component.scss

CU-85ztfh804_z-index--_Egor

---

src/app/office/shared/member-card/member-card.component.html
src/app/office/shared/member-card/member-card.component.scss
src/app/ui/components/tag/tag.component.scss

CU-85ztfhejn_-----_Egor

---

src/app/office/members/members.resolver.spec.ts
src/app/office/office.module.ts
src/app/office/program/detail/detail-routing.module.ts
src/app/office/program/detail/detail.module.ts
src/app/office/program/detail/detail/detail.component.html
src/app/office/program/detail/members/members.component.html
src/app/office/program/detail/members/members.component.scss
src/app/office/program/detail/members/members.component.spec.ts
src/app/office/program/detail/members/members.component.ts
src/app/office/program/detail/members/members.resolver.spec.ts
src/app/office/program/detail/members/members.resolver.ts
src/app/office/program/detail/projects/projects.component.html
src/app/office/program/detail/projects/projects.component.scss
src/app/office/program/detail/projects/projects.component.spec.ts
src/app/office/program/detail/projects/projects.component.ts
src/app/office/program/detail/projects/projects.resolver.spec.ts
src/app/office/program/detail/projects/projects.resolver.ts
src/app/office/program/program.module.ts
src/app/office/program/services/program.service.ts
src/app/office/program/shared/program-head/program-head.component.html
src/app/office/program/shared/program-head/program-head.component.scss
src/app/office/program/shared/program-head/program-head.component.spec.ts
src/app/office/program/shared/program-head/program-head.component.ts
src/app/office/projects/projects.resolver.spec.ts

CU-85ztkgr7q_Make-projects--members-tabs-for-programs_Egor

---

src/app/office/program/detail/detail.module.ts
src/app/office/program/detail/main/main.component.html
src/app/office/program/detail/main/main.component.scss
src/app/office/program/detail/main/main.component.ts
src/app/office/program/models/program.model.ts
src/app/office/program/program.module.ts
src/app/office/program/services/program-news.service.spec.ts
src/app/office/program/services/program-news.service.ts
src/app/office/program/shared/news-card/news-card.component.html
src/app/office/program/shared/news-card/news-card.component.scss
src/app/office/program/shared/news-card/news-card.component.spec.ts
src/app/office/program/shared/news-card/news-card.component.ts
src/app/office/projects/detail/detail.module.ts
src/app/office/projects/detail/shared/news-card/news-card.component.html
src/app/office/projects/models/project-news.model.ts

CU-85ztkqwua_program-news--contacts_Egor

---

src/app/office/program/detail/main/main.component.html
src/app/office/shared/sidebar/sidebar.component.html

CU-85ztqebxr_------_Egor

---

src/app/office/program/detail/main/main.component.html

CU-85ztqebky_-----_Egor

---

src/app/office/projects/detail/info/info.component.html

CU-85ztqecz5_---_Egor

---

src/app/office/office.component.html
src/app/office/shared/sidebar/sidebar.component.scss

CU-85ztqec57_----_Egor

---

src/app/auth/models/user.model.ts
src/app/office/members/members.component.html
src/app/office/members/members.component.spec.ts
src/app/office/members/members.component.ts
src/app/office/members/members.resolver.ts
src/app/office/mentors/mentors.component.html
src/app/office/mentors/mentors.component.spec.ts
src/app/office/mentors/mentors.component.ts
src/app/office/mentors/mentors.resolver.ts
src/app/office/services/member.service.ts

CU-85ztdkqxj_-----_Egor

---

src/app/office/shared/member-card/member-card.component.html

CU-85ztfrtxd_----_Egor

---

src/app/office/projects/detail/info/info.component.scss
src/app/office/projects/detail/shared/news-card/news-card.component.scss
src/app/office/shared/project-card/project-card.component.scss

CU-85ztfhczt_------_Egor

---

src/app/office/program/detail/members/members.component.spec.ts
src/styles/components/_bar.scss

CU-85zt3udmu_--_Dmitry

---

src/app/auth/auth-routing.module.ts
src/app/auth/auth.module.ts
src/app/auth/confirm-password-reset/confirm-password-reset.component.html
src/app/auth/confirm-password-reset/confirm-password-reset.component.spec.ts
src/app/auth/confirm-password-reset/confirm-password-reset.component.ts
src/app/auth/login/login.component.html
src/app/auth/login/login.component.scss
src/app/auth/reset-password/reset-password.component.html
src/app/auth/reset-password/reset-password.component.scss
src/app/auth/reset-password/reset-password.component.spec.ts
src/app/auth/reset-password/reset-password.component.ts
src/app/auth/services/auth.service.ts
src/app/auth/set-password/set-password.component.html
src/app/auth/set-password/set-password.component.scss
src/app/auth/set-password/set-password.component.spec.ts
src/app/auth/set-password/set-password.component.ts
src/styles/_global.scss
src/styles/pages/auth.scss

CU-862kafxnq_--_Egor

---

src/app/auth/register/register.component.html
src/app/auth/register/register.component.ts
src/styles/_global.scss

CU-8692rjq76_--------_Egor

---

src/app/ui/components/snackbar/snackbar.component.scss

CU-8692rpmme__Egor

---

src/app/office/profile/edit/edit.component.html
src/app/office/projects/edit/edit.component.html
src/app/office/projects/edit/edit.component.scss
src/styles/_global.scss

CU-85ztht75a_------_Egor

---

src/app/office/program/detail/main/main.component.html
src/app/office/program/detail/main/main.component.scss

CU-8692w1cqg_---_Egor

---

src/app/ui/components/avatar-control/avatar-control.component.html
src/app/ui/components/avatar-control/avatar-control.component.scss

CU-85ztpgaw0_---_Egor

---

src/app/auth/models/user.model.ts
src/app/office/chat/models/chat-item.model.ts
src/app/office/chat/shared/chat-card/chat-card.component.html
src/app/office/shared/member-card/member-card.component.html
src/app/office/shared/member-card/member-card.component.ts
src/app/ui/components/avatar/avatar.component.html
src/app/ui/components/avatar/avatar.component.scss
src/app/ui/components/avatar/avatar.component.ts
src/app/ui/components/chat-message/chat-message.component.html

CU-8692waa4d_----_Egor

---

src/app/core/services/websocket.service.ts
src/app/office/models/chat.model.ts
src/app/office/office.component.ts
src/app/office/profile/detail/profile-detail.component.html
src/app/office/profile/detail/profile-detail.component.spec.ts
src/app/office/profile/detail/profile-detail.component.ts
src/app/office/services/chat.service.ts

CU-8692xvje1_--_Egor

---

src/app/office/chat/shared/chat-card/chat-card.component.ts
src/app/office/members/filters/members-filters.component.ts
src/app/office/program/detail/shared/news-card/news-card.component.ts
src/app/office/program/shared/program-card/program-card.component.ts
src/app/office/program/shared/program-head/program-head.component.ts
src/app/office/shared/advert-card/advert-card.component.ts
src/app/office/shared/chat-window/chat-window.component.ts
src/app/office/shared/invite-card/invite-card.component.ts
src/app/office/shared/invite-manage-card/invite-manage-card.component.ts
src/app/office/shared/member-card/member-card.component.ts
src/app/office/shared/news-card/news-card.component.ts
src/app/office/shared/project-card/project-card.component.ts
src/app/office/shared/response-card/response-card.component.ts
src/app/office/shared/sidebar/sidebar.component.ts
src/app/ui/components/avatar/avatar.component.ts
src/app/ui/components/chat-message/chat-message.component.ts
src/app/ui/components/checkbox/checkbox.component.ts
src/app/ui/components/icon/icon.component.ts
src/app/ui/components/modal/modal.component.ts
src/app/ui/components/profile-info/profile-info.component.ts
src/app/ui/components/select/select.component.ts
src/app/ui/components/switch/switch.component.ts

Gregortokarev pro 66

---

src/app/office/profile/detail/main/main.component.html
src/app/office/profile/detail/main/main.component.ts
src/app/office/shared/news-form/news-form.component.html
src/app/office/shared/news-form/news-form.component.ts

Gregortokarev pro 187

---

projects/social_platform/src/app/ui/components/file-item/file-item.component.html
projects/social_platform/src/app/ui/components/file-item/file-item.component.ts

Убрал использование метода toUpperCase на использование uppercase Pipe

change toUpperCase to uppercase Pipe

---

projects/skills/src/app/profile/home/profile-home.routes.ts
projects/skills/src/app/profile/home/subscription-plans/subscription-plans.component.html
projects/skills/src/app/profile/home/subscription-plans/subscription-plans.component.ts
projects/skills/src/app/profile/home/subscription-plans/subscription-plans.resolver.ts
projects/skills/src/app/profile/services/subscription-plans.service.ts
projects/skills/src/models/subscription.model.ts

Сделал сервис с получением подписок, распределли их вместо мок массива. Также сделал interface для плана подписок

add subscriptions from backend

---

projects/skills/src/app/profile/home/subscription-plans/subscription-plans.component.scss

Исправил верстку в соответсвии с фигмой

Fix Layout subscription plan
